### PR TITLE
Finlay

### PR DESCRIPTION
**Pull request by finlaycampbell**
Contact likelihood/priors/moves now implemented in Rcpp and passing checks!

### CODE REVIEW

**Comment by thibautjombart** [comment]
@finlaycampbell this branch is based on an old version of the master, so the merging might get messy. Would you mind rebasing the branch on the current master, and then PR again? Or use `git cherry-pick` as suggested by @richfitz e.g.
```
git checkout -b contacts
git cherry-pick 7cc7f20 c4c5e6f
```

**Comment by finlaycampbell** [comment]
I've branched from the current master and cherry-picked the changes - can you make a branch called contacts that I can PR to?

**Comment by thibautjombart** [comment]
Done. You should be able to PR against origin/contacts now

**Comment by finlaycampbell** [comment]
Done!

**Pull request merged**
